#!/bin/bash

function trap_ctrlc()
	{
		echo 'Stoping docker container ...'
		docker stop php;
		# echo 'Launching php on the computer';
		# sudo service php start;
		exit 0;
	}

version=7.0
# for arg in "$@"; do
# 	if [ "$arg" = "5.6" ]
# 	then
# 		version=5.6
# 	fi
# done

trap "trap_ctrlc" 2

# echo 'Stoping php on the computer ...';
# sudo service php stop;
# sudo service mysql stop;
# sudo pkill mysqld;
echo 'Launching docker container ...'
cat >> Dockerfile <<EOF
FROM php:7.0-fpm-alpine AS php

# Install php extensions
RUN docker-php-ext-install pdo 			\
	&& docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install mysqli	\
	&& rm -rf /var/lib/apt/lists/*

# Run php in foreground and as root
CMD ["php-fpm", "-F", "-R"]
EOF
docker build .
docker run -it -d -p 9000:9000 --rm --name php php:$version
rm Dockerfile

while :
do
	echo "Hit [CTRL+C] to stop!";
	read default;
done