#!/bin/bash

if [ -z "$1" ]
then
	echo ""
	echo 'Missing argument for checking if service exists ...' >&2
		echo 'Normal use : serviceExists name' >&2
	echo ""
	exit 1
fi

service --status-all | grep -Fq "$1";

if [ $? == 0 ]
then
	echo 'Yes';
else
	echo 'No';
fi